#!/bin/bash
#BATCH -J PartProdPartialSum
#SBATCH --ntasks 10 
#SBATCH --nodes 5
#SBATCH --tasks-per-node 2
#SBATCH --mem-per-cpu 2GB
#SBATCH --partition partition 
#SBATCH --account=students

cd $SLURM_SUBMIT_DIR

module load openmpi

mpirun --mca opal_warn_on_missing_libcuda 0 -np 10 ./partialSum
