#!/bin/bash
#SBATCH -J PartProdHello
#SBATCH --ntasks 40
#SBATCH --nodes 5
#SBATCH --tasks-per-node 8
#SBATCH --mem-per-cpu 2GB
#SBATCH --partition partition
#SBATCH --account=students

cd $SLURM_SUBMIT_DIR

module load openmpi

mpirun --mca opal_warn_on_missing_libcuda 0 -np 40 ./hello
