#!/bin/bash
#BATCH -J PartProdSum
#SBATCH --ntasks 10 
#SBATCH --nodes 10
#SBATCH --tasks-per-node 1
#SBATCH --mem-per-cpu 2GB
#SBATCH --partition partition 
#SBATCH --account=students

cd $SLURM_SUBMIT_DIR

module load openmpi

mpirun --mca opal_warn_on_missing_libcuda 0 -np 10 ./SumModified
